name: Run Renovate

on:
    schedule:
        - cron: '0 11 * * *' # Every day at 11am UTC
    workflow_dispatch:

jobs:
    renovate:
        name: Run Renovate
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2

            - name: Run Renovate
              uses: renovatebot/github-action@7b4b65bf31e07d4e3e51708d07700fb41bc03166 #46.1.3
              with:
                  configurationFile: renovate-config.json
                  token: ${{ secrets.PAT }}
